### ISSUE TITLE
Test own data?

### ISSUE THREAD

**Issue by AIisCool** [JingyunLiang/VRT#1]
Hi, very impressed by the results. Is there a way to test my own data with the models?

Thank you.

**Comment by JingyunLiang** [comment]
Just change `--folder_lq` and `--folder_gt` to your own paths (using similar folder structure as `REDS4/GT/000/*.png`) .
```
python main_test_vrt.py --task 001_VRT_videosr_bi_REDS_6frames --folder_lq testsets/REDS4/sharp_bicubic --folder_gt testsets/REDS4/GT --tile 40 128 128 --tile_overlap 2 20 20
```
