### ISSUE TITLE
Memory consumption while training

### ISSUE THREAD

**Issue by xg416** [JingyunLiang/VRT#10]
Hi, congrats on this cool work! 
I'm trying to train your model but I only have 2 A100 GPUs so the memory is limited, I wonder how much space do you need to train models like "003_VRT_videosr_bi_Vimeo_7frames.pth" and "006_VRT_videodeblurring_GoPro.pth"?

**Comment by JingyunLiang** [comment]
28GB and 31GB per training video sequence, respectively. One can use torch.utils.checkpoint to reduce memory usage significantly at the expense of longer training time.

**Comment by xg416** [comment]
> 

Thanks!
