### ISSUE TITLE
RuntimeError expected input... to have 28 channels, but got 27 channels instead

### ISSUE THREAD

**Issue by ialhashim** [JingyunLiang/VRT#14]
I am getting this error on my own test data (with task 008_VRT_videodenoising_DAVIS)

`RuntimeError: Given groups=1, weight of size [96, 28, 1, 3, 3], expected input[1, 27, 32, 128, 128] to have 28 channels, but got 27 channels instead`

Full stack:
`  File "C:\Dev\VRT\models\network_vrt.py", line 1395, in forward
    x = self.conv_first(x.transpose(1, 2))
  File "C:\tools\miniconda3\envs\pt\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\tools\miniconda3\envs\pt\lib\site-packages\torch\nn\modules\conv.py", line 590, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\tools\miniconda3\envs\pt\lib\site-packages\torch\nn\modules\conv.py", line 585, in _conv_forward
    return F.conv3d(
RuntimeError: Given groups=1, weight of size [96, 28, 1, 3, 3], expected input[1, 27, 32, 128, 128] to have 28 channels, but got 27 channels instead`

**Comment by JingyunLiang** [comment]
We add noises in the network forward() function. Make sure `nonblind_denoising == True` here:
https://github.com/JingyunLiang/VRT/blob/c033a79d25aa802f175685e4f1095481e25d481a/models/network_vrt.py#L1376

**Comment by ialhashim** [comment]
I see. So this network is trained on a specific kind of noise correct?

**Comment by JingyunLiang** [comment]
Yes.  Following FastDVDNet and PaCNet, we train non-blind denoising models for fair quantitative comparison.

**Comment by Gyudori** [comment]
So, do we need 4 channel input image for testing denoising?
And if then, where can I get noise-level-map(4th channel) from?

**Comment by JingyunLiang** [comment]
The input is 3 channel. We add noise-level-map as following:
> We add noises in the network forward() function. Make sure `nonblind_denoising == True` here:
> 
> https://github.com/JingyunLiang/VRT/blob/c033a79d25aa802f175685e4f1095481e25d481a/models/network_vrt.py#L1376

**Comment by WEIZHIHONG720** [comment]
I meet  new problem:deform_conv2d() takes from 3 to 7 positional arguments but 8 were given !\ @JingyunLiang @Gyudori
