### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 426) exited unexpectedly

### ISSUE THREAD

**Issue by maheshs11** [JingyunLiang/VRT#19]
![image](https://user-images.githubusercontent.com/7268915/154297293-07c23f9c-01d6-4ca6-a257-00cf5a218888.png)

**Comment by JingyunLiang** [comment]
Did u test it on your own machine or Colab? Try to use `num_works=1`:
https://github.com/JingyunLiang/VRT/blob/c033a79d25aa802f175685e4f1095481e25d481a/main_test_vrt.py#L53

**Comment by maheshs11** [comment]
> Did u test it on your own machine or Colab? Try to use `num_works=1`:
> 
> https://github.com/JingyunLiang/VRT/blob/c033a79d25aa802f175685e4f1095481e25d481a/main_test_vrt.py#L53

in colab

**Comment by maheshs11** [comment]
i reduced my video to 3 seconds , the issue was gone ,but no result generated.
![image](https://user-images.githubusercontent.com/7268915/154302450-ee5f60db-98e5-441c-86bd-dfffd7500bd5.png)

**Comment by maheshs11** [comment]
reduced video dimension to 540*640 the issue was gone.

**Comment by darkzbaron** [comment]
Anyway to use that on colab without resizing, that defeats the purpose
