### ISSUE TITLE
I find it it's training is too slow in 8 V100, could you give me some advice?

### ISSUE THREAD

**Issue by yishionsunshine** [JingyunLiang/VRT#20]

**Comment by JingyunLiang** [comment]
Which experiments are you doing? Do you use too much `torch.utils.checkpoint`? It can save 2/3 memory but would be 3-4 times slower.

**Comment by yishionsunshine** [comment]
> Which experiments are you doing? Do you use too much `torch.utils.checkpoint`? It can save 2/3 memory but would be 3-4 times slower.

I want to recurrent SR model and I use the traing codes directy nothing changed but the config json file.

**Comment by JingyunLiang** [comment]
For 6-frame Video SR on REDS, it takes about 3-4 days to train the model on 8 A100 GPUs. V100 might be slower and I guess it's about 5-6 days, right?

**Comment by yishionsunshine** [comment]
Thanks for your help! you do me a greate favor.
