### ISSUE TITLE
Colab path error

### ISSUE THREAD

**Issue by jarredou** [JingyunLiang/VRT#21]
Hello !

I wanted to try VRT with the proposed Colab notebook with one of my own test video but while I've changed nothing to the notebook, and use the embedded upload function, the frames are generated without problem but then I'm getting this error when running the "default" inference command provided :
`!python main_test_vrt.py --task 001_VRT_videosr_bi_REDS_6frames --folder_lq testsets/uploaded --tile 6 128 128 --tile_overlap 2 20 20
`
```
[...]
loading model from ./model_zoo/vrt/model_zoo/vrt/001_VRT_videosr_bi_REDS_6frames.pth
using dataset from testsets/uploaded/
Traceback (most recent call last):
  File "main_test_vrt.py", line 346, in <module>
    main()
  File "main_test_vrt.py", line 51, in main
    'sigma':args.sigma, 'num_frame':-1, 'cache_data': False})
  File "/content/VRT/data/dataset_video_test.py", line 349, in __init__
    img_paths_lq = sorted(list(utils_video.scandir(subfolder_lq, full_path=True)))
  File "/content/VRT/utils/utils_video.py", line 37, in _scandir
    for entry in os.scandir(dir_path):
NotADirectoryError: [Errno 20] Not a directory: 'testsets/uploaded/BI_deinterlaced_1000frames.mp4'
```
 and I don't understand why, so hard to fix it by myself, any help would be appreciated !

**Comment by JingyunLiang** [comment]
Thanks for your reporting. The bug is fixed.
