### ISSUE TITLE
Colab inference problem

### ISSUE THREAD

**Issue by ryzen3100** [JingyunLiang/VRT#23]
Hi,
The colab demo crashes (^C exits) when running the inference tab using self-provided images/video.
I have tried .png sequence, .mp4 video neither worked.
The included (gt) samples work fine.

**Comment by JingyunLiang** [comment]
I think it's because you upload too many frames/ long videos.

**Comment by Timmate** [comment]
I guess it would make sense to print a help message with this info to help users troubleshoot this problem faster.
