### ISSUE TITLE
Same error, solution didn't work: RuntimeError expected input... to have 28 channels, but got 27 channels instead

### ISSUE THREAD

**Issue by dkoslicki** [JingyunLiang/VRT#24]
I ran into the same error as #14 , and verified that `self.nonblind_denoising` was set to `True` [here](https://github.com/JingyunLiang/VRT/blob/c033a79d25aa802f175685e4f1095481e25d481a/models/network_vrt.py#L1376), but still receive the error:
```
line 585, in _conv_forward
    return F.conv3d(
RuntimeError: Given groups=1, weight of size [96, 28, 1, 3, 3], expected input[1, 27, 40, 128, 128] to have 28 channels, but got 27 channels instead
```
This is using the dataset `VRT/testsets/REDS4/sharp_bicubic` via the call `python main_test_vrt.py --task 008_VRT_videodenoising_DAVIS --folder_lq testsets/REDS4/sharp_bicubic --tile 40 128 128 --tile_overlap 2 20 20`. I ultimately want to run this on my own folder of PNGs from a video.

**Comment by JingyunLiang** [comment]
It's a bug. Try to add `--sigma 1` for quick fix. It should output similar results as no added noise. We will fix it later.

Also note that we train it as a non-blind denoising model. You may need to try different sigmas (e.g., larger sigma if the video is heavily corrupted by Gaussian noise).

**Comment by dkoslicki** [comment]
I see; but unfortunately `--sigma 1` did not fix the issue: I got the exact same error message.

**Comment by JingyunLiang** [comment]
I see. It's because you didn't specify --folder_gt, so it uses another dataloader. We did not provide an interface for lq-only-input in denoising.

**Comment by haikunzhang95** [comment]
> It's a bug. Try to add `--sigma 1` for quick fix. It should output similar results as no added noise. We will fix it later.
> 
> Also note that we train it as a non-blind denoising model. You may need to try different sigmas (e.g., larger sigma if the video is heavily corrupted by Gaussian noise).

Have you fixed the bug?
