### ISSUE TITLE
Test in clips leads to block artifact

### ISSUE THREAD

**Issue by EricMingze** [JingyunLiang/VRT#26]
Thanks for sharing your impressive work!

I got a problems regards to the video deblur task. I noticed there are block artifacts in the GOPRO test result you released(e.g. 00000097_005_VRT_GoPro.png, 00000098_005_VRT_GoPro.png in GOPR0410_11_00 folder, 006_VideoDeblur_VRT_6frames_GoPro). This artifact is much worse when I run the pretrained model with my own data.

I think this might caused by testing frames in clips, so there is no information flowing between different clips. Do you have any idea on this?

Thanks for help.
![00000097_005_VRT_GoPro](https://user-images.githubusercontent.com/65255547/157945378-f8a5b844-a80f-4b45-9e48-1fd241b79c7f.png)
![00000098_005_VRT_GoPro](https://user-images.githubusercontent.com/65255547/157945657-5b3e1950-fb9b-4df7-b160-951bed87fb21.png)

**Comment by JingyunLiang** [comment]
Yes. We partition it spatially to be patches due to memory limit. The ideal way is to test it as a complete image. This model is far from perfect, and we are working on reducing the memory consumption.
