### ISSUE TITLE
I tested video SR with SwinIR and VRT, but SwinIR perfroms better. Is it normal?

### ISSUE THREAD

**Issue by JunjieCharles** [JingyunLiang/VRT#27]
VRT testing command
```
CUDA_VISIBLE_DEVICES=9 \
python main_test_vrt.py --task 002_VRT_videosr_bi_REDS_16frames \
                        --folder_lq /home/liao/cjj/dataset/test/LR \
                        --folder_gt /home/liao/cjj/dataset/test/GT \
                        --tile 10 128 128 \
                        --tile_overlap 2 20 20
```

SwinIR model: 001_classicalSR_DIV2K_s48w8_SwinIR-M_x4

Video for testing: https://cowtransfer.com/s/1739646a86874e

Result

SwinIR |   |   |   |   |  
-- | -- | -- | -- | -- | --
  | 1 | 2 | 3 | 4 | 平均
PSNR | 26.9603 | 31.9831 | 33.0922 | 33.2781 | 31.32843
SSIM | 0.7353 | 0.9022 | 0.8842 | 0.9233 | 0.86125
VRT |   |   |   |   |  
  | 1 | 2 | 3 | 4 | 平均
PSNR | 26.7961 | 31.7153 | 30.7655 | 34.3461 | 30.90575
SSIM | 0.7272 | 0.8931 | 0.8724 | 0.9385 | 0.8578

**Comment by JingyunLiang** [comment]
It's strange. SwinIR cannot utilize nay temporal information. How is your LR image generated?

**Comment by JunjieCharles** [comment]
The dataset is from [https://github.com/lovepiano/SMFN_For_360VSR/](url)

As stated in his paper, 

> Then considering the limitation of computing resources, we downsample each video with scale factor 2 to resolution ranging from 2,048×1024 to 720×360 using the bicubic interpolation algorithm as the ground truth. Then we further downsample the ground truth videos with scale factor 4 using the same interpolation algorithm to obtain the corresponding LR videos.

**Comment by JingyunLiang** [comment]
LR is not actually directly downsampled (bicubic) from HR. This might be the reason. One may need to retrain it on the new dataset to achieve best performance.

**Comment by JunjieCharles** [comment]
I'll try it. Thanks!

**Comment by JunjieCharles** [comment]
I just found that the model trained on Vimeo is better than REDS, which performs better than SwinIR. I think maybe the model trained on Vimeo has better generalization ability.
