### ISSUE TITLE
Change upscale arg for VideoSR

### ISSUE THREAD

**Issue by ArfaSaif** [JingyunLiang/VRT#29]
I am running the VRT demo code and would like to change the upscale ratio to 2x instead of the default of 4 on the `001_VRT_videosr_bi_REDS_6frames` task. I am using my own test dataset containing 1080x1920p image files. I'm running  `python main_test_vrt.py --task 001_VRT_videosr_bi_REDS_6frames --folder_lq testsets/uploaded --tile 40 128 128 --tile_overlap 2 20 20`... 

I noticed that the upscale is being set in `main_test_vrt.py`. Simply changing `upscale=2` doesn't work because of model mismatch errors during model load.
Is there a pretrained model that will do a 2x upscale or are there a set of parameters that I can pass when initializing the model for the 2x upscale to work?

```
 # define model
    if args.task == '001_VRT_videosr_bi_REDS_6frames':
        model = net(upscale=4, img_size=[6,64,64], window_size=[6,8,8], depths=[8,8,8,8,8,8,8, 4,4,4,4, 4,4],
                    indep_reconsts=[11,12], embed_dims=[120,120,120,120,120,120,120, 180,180,180,180, 180,180],
                    num_heads=[6,6,6,6,6,6,6, 6,6,6,6, 6,6], pa_frames=2, deformable_groups=12)
        datasets = ['REDS4']
        args.scale = 4
        args.window_size = [6,8,8]
        args.nonblind_denoising = False
```
Thanks!

**Comment by JingyunLiang** [comment]
No. X2 is not supported yet.
