### ISSUE TITLE
Few questions about paper 😸 

### ISSUE THREAD

**Issue by machineko** [JingyunLiang/VRT#3]
According to the paper "The runtime is 2.2s per frame on 1280×720 blurred videos". What gpu are you guys used to measure runtime?  
Also i have question about model size, Did you guys try smaller model sizes (popular in modern transformers something like VRT-S VRT-L with different parameter size etc.) or architecture is limited and don't coverage with custom sizes?

And ofc. congrats on cool paper 📦

**Comment by leefly072** [comment]
Could you share the code of test model runtime  ? Thanks
