### ISSUE TITLE
Testing fails in network_vrt.py @ get_flow_4frames, flows_forward[0].shape[1]

### ISSUE THREAD

**Issue by amrosado** [JingyunLiang/VRT#38]
Hi, I've been trying to use this code in combination with the github://cszn/KAIR for training a VRT model using my data and a custom dataloader I wrote for my data.  Unfortunately, I'm running into an error in the testing phase of the get_flow_4frames because the shape of the forward_flows[0] is: torch.Size([1, 0, 2, 64, 64])

The X input into forward is: torch.Size([1, 1, 3, 64, 64])
The X input into get_flows is: torch.Size([1, 1, 3, 64, 64])
The X input into get_flow_2frames:  torch.Size([1, 1, 3, 64, 64])
The forward_flows[0] is as previously specified: torch.Size([1, 0, 2, 64, 64])

```
def get_flow_4frames(self, flows_forward, flows_backward):
        '''Get flow between t and t+2 from (t,t+1) and (t+1,t+2).'''

        # backward
        d = flows_forward[0].shape[1]
        flows_backward2 = []
        for flows in flows_backward:
            flow_list = []
            for i in range(d - 1, 0, -1):
                flow_n1 = flows[:, i - 1, :, :, :]  # flow from i+1 to i
                flow_n2 = flows[:, i, :, :, :]  # flow from i+2 to i+1
                flow_list.insert(0, flow_n1 + flow_warp(flow_n2, flow_n1.permute(0, 2, 3, 1)))  # flow from i+2 to i
            if len(flow_list) != 0:
                flows_backward2.append(torch.stack(flow_list, 1))
```

The training is working without any issues.

Is this the anticipated behavior within the code or is there something regarding the test settings that I'm missing?

**Comment by JingyunLiang** [comment]
If X input into forward is: torch.Size([1, 1, 3, 64, 64]), there is no definition of getting flow between t and t+2  frames.

**Comment by amrosado** [comment]
Yes, I determined that I implemented my testing data loader incorrectly.  For my application, I wanted something that would systematically work through every frame, but I could not provide the entire image sequence at all given the limited amount of memory I had access to.  After fixing my testing data loader I was able test without issue.  Thank you so much for you help.
