### ISSUE TITLE
Huggingface Spaces

### ISSUE THREAD

**Issue by AK391** [JingyunLiang/VRT#4]
Hi, would you be interested in sharing a web demo on Huggingface Spaces for VRT?

 It would make this model more accessible as it would allow people to try out the model directly from the browser. Some other recent machine learning model repos have set up Spaces for easy access:

github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

Spaces is completely free, and I am to help setup a Gradio Space. Here are some getting started instructions if you'd prefer to do it yourself: https://huggingface.co/blog/gradio-spaces

**Comment by JingyunLiang** [comment]
Thanks for your help. I am glad to see it on Huggingface Spaces.
