### ISSUE TITLE
RuntimeError: [enforce fail at alloc_cpu.cpp:73] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 116813856768 bytes. Error code 12 (Cannot allocate memory)

### ISSUE THREAD

**Issue by codeliger** [JingyunLiang/VRT#49]
RuntimeError: [enforce fail at alloc_cpu.cpp:73] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 116813856768 bytes. Error code 12 (Cannot allocate memory)

Any idea how to fix this?

i got 16GB of ram

**Comment by zan-dong** [comment]
maybe try a small one
